const isJapaneseLocale =
  typeof window !== "undefined" && window.APP_SETTINGS?.language_code?.toLowerCase().startsWith("ja");

const HOTKEY_JA_TRANSLATIONS = {"Submit Annotation": "アノテーションを送信", "Submit the current annotation": "現在のアノテーションを送信", "Skip Task": "タスクをスキップ", "Skip the current task": "現在のタスクをスキップ", "Undo": "元に戻す", "Undo last action": "直前の操作を元に戻す", "Redo": "やり直し", "Redo previously undone action": "元に戻した操作をやり直す", "Focus Previous Task": "前のタスクにフォーカス", "Move focus to the previous task": "前のタスクにフォーカスを移動", "Focus Next Task": "次のタスクにフォーカス", "Move focus to the next task": "次のタスクにフォーカスを移動", "Focus Closed Task": "クローズ済みタスクにフォーカス", "Focus on the closed task column": "クローズ済みタスク列にフォーカス", "Focus Open Task": "オープンタスクにフォーカス", "Focus on the open task column": "オープンタスク列にフォーカス", "Toggle Bulk Sidebar": "一括サイドバー切替", "Minimize or expand bulk actions sidebar": "一括操作サイドバーを最小化/展開", "Delete All Regions": "全リージョンを削除", "Remove all regions": "すべてのリージョンを削除", "Focus First Region": "最初のリージョンにフォーカス", "Move focus to the first focusable region": "最初にフォーカス可能なリージョンへ移動", "Create Region Relation": "リージョン関連付けを作成", "Create a relation between selected regions": "選択リージョン間の関連を作成", "Toggle Region Visibility": "リージョン表示切替", "Show or hide the selected region": "選択リージョンの表示/非表示", "Toggle All Region Visibility": "全リージョン表示切替", "Show or hide all regions": "全リージョンの表示/非表示", "Lock Region": "リージョンをロック", "Lock or unlock the selected region": "選択リージョンをロック/解除", "Edit Region Metadata": "リージョンメタデータ編集", "Edit metadata for selected region": "選択リージョンのメタデータを編集", "Unselect Region": "リージョン選択解除", "Deselect the currently selected region": "現在選択中のリージョンを解除", "Exit Region Mode": "リージョンモード終了", "Exit relation mode and unselect region": "関連モードを終了してリージョン選択解除", "Delete Selected Region": "選択リージョンを削除", "Delete currently selected region": "現在選択中のリージョンを削除", "Cycle Regions": "リージョンを巡回", "Cycle through all regions": "すべてのリージョンを順に切替", "Duplicate Region": "リージョンを複製", "Create a copy of the selected region": "選択リージョンのコピーを作成", "Delete Segment": "セグメントを削除", "Delete selected segment": "選択セグメントを削除", "Rewind 1 Second": "1秒巻き戻し", "Rewind the audio by 1 second": "音声を1秒巻き戻す", "Play / Pause Audio": "音声再生/一時停止", "Toggle audio playback": "音声再生を切り替え", "Step Back": "1フレーム戻る", "Step back one frame": "1フレーム戻る", "Step Forward": "1フレーム進む", "Step forward one frame": "1フレーム進む", "Play / Pause Video": "動画再生/一時停止", "Toggle video playback": "動画再生を切り替え", "Step one frame backward": "1フレーム戻る", "Step one frame forward": "1フレーム進む", "Previous Keyframe": "前のキーフレーム", "Jump to previous keyframe": "前のキーフレームへ移動", "Next Keyframe": "次のキーフレーム", "Jump to next keyframe": "次のキーフレームへ移動", "Seek Backward": "巻き戻し", "Seek video backward": "動画を巻き戻す", "First Frame": "最初のフレーム", "Jump to first frame": "最初のフレームへ移動", "Seek Forward": "早送り", "Seek video forward": "動画を早送り", "Last Frame": "最後のフレーム", "Jump to last frame": "最後のフレームへ移動", "Hop Backward": "大きく戻る", "Hop backward quickly": "素早く大きく戻る", "Hop Forward": "大きく進む", "Hop forward quickly": "素早く大きく進む", "Zoom In": "拡大", "Zoom in on the image": "画像を拡大", "Pan Image": "画像をパン", "Pan around the image": "画像をドラッグ移動", "Zoom to Fit": "全体表示", "Zoom to fit the full image in view": "画像全体が収まるよう表示", "Zoom to 100%": "100%表示", "Zoom to actual image size (100%)": "実サイズ(100%)で表示", "Zoom Out": "縮小", "Zoom out of the image": "画像を縮小", "Move Tool": "移動ツール", "Select the move tool to reposition annotations": "注釈を移動する移動ツールを選択", "Brush Tool": "ブラシツール", "Select the brush tool": "ブラシツールを選択", "Ellipse Tool": "楕円ツール", "Select the ellipse tool": "楕円ツールを選択", "Eraser Tool": "消しゴムツール", "Select the eraser tool": "消しゴムツールを選択", "Auto Detect": "自動検出", "Use the auto-detect tool to automatically suggest regions": "自動検出ツールでリージョン候補を提案", "Key Point Tool": "キーポイントツール", "Select the key point annotation tool": "キーポイント注釈ツールを選択", "Magic Wand": "マジックワンド", "Select the magic wand tool for smart region selection": "スマート選択用マジックワンドを選択", "Polygon Tool": "ポリゴンツール", "Select the polygon annotation tool": "ポリゴン注釈ツールを選択", "Rectangle Tool": "矩形ツール", "Select the rectangle annotation tool": "矩形注釈ツールを選択", "3-Point Rectangle": "3点矩形", "Draw a rotated rectangle using 3-point selection": "3点指定で回転矩形を描画", "Rotate Left": "左回転", "Rotate the image 90° to the left": "画像を左に90°回転", "Rotate Right": "右回転", "Rotate the image 90° to the right": "画像を右に90°回転", "Decrease Tool Size": "ツールサイズを小さく", "Decrease tool size": "ツールサイズを縮小", "Increase Tool Size": "ツールサイズを大きく", "Increase tool size": "ツールサイズを拡大", "Extend Left": "左へ拡張", "Extend the region to the left": "リージョンを左に拡張", "Extend Right": "右へ拡張", "Extend the region to the right": "リージョンを右に拡張", "Shrink Left": "左を縮小", "Shrink the region from the left": "リージョンの左側を縮小", "Shrink Right": "右を縮小", "Shrink the region from the right": "リージョンの右側を縮小", "Extend Left (Large)": "左へ大きく拡張", "Extend region left significantly": "リージョンを左へ大きく拡張", "Extend Right (Large)": "右へ大きく拡張", "Extend region right significantly": "リージョンを右へ大きく拡張", "Shrink Left (Large)": "左を大きく縮小", "Shrink region from left significantly": "リージョン左側を大きく縮小", "Shrink Right (Large)": "右を大きく縮小", "Shrink region from right significantly": "リージョン右側を大きく縮小", "Previous Image": "前の画像", "View previous image": "前の画像を表示", "Next Image": "次の画像", "View next image": "次の画像を表示", "Next Phrase": "次のフレーズ", "Navigate to the next phrase in paragraph view": "段落ビューで次のフレーズへ移動", "Previous Phrase": "前のフレーズ", "Navigate to the previous phrase in paragraph view": "段落ビューで前のフレーズへ移動", "Select All and Annotate": "すべて選択して注釈", "Select all text in current phrase and create annotation": "現在フレーズのテキストを全選択して注釈作成", "Next Region in Phrase": "フレーズ内の次リージョン", "Navigate to the next region within current phrase": "現在フレーズ内の次リージョンへ移動", "Previous Region in Phrase": "フレーズ内の前リージョン", "Navigate to the previous region within current phrase": "現在フレーズ内の前リージョンへ移動", "Annotation Actions": "アノテーション操作", "Shortcuts for common annotation tasks like submit, skip, undo and redo": "送信・スキップ・元に戻す・やり直しなど、一般的なアノテーション作業のショートカット", "Data Manager": "データマネージャー", "Shortcuts for navigating and managing tasks in Project's Data Manager": "プロジェクトのデータマネージャーでタスクを移動・管理するためのショートカット", "Region Management": "リージョン管理", "Shortcuts for creating, selecting and manipulating annotation regions": "アノテーション領域の作成・選択・操作のためのショートカット", "Tools": "ツール", "Shortcuts for controlling tools panel when labeling images": "画像ラベリング時のツールパネル操作ショートカット", "Audio Controls": "音声コントロール", "Shortcuts for controlling audio playback and navigation": "音声の再生とナビゲーションを操作するショートカット", "Video Controls": "動画コントロール", "Shortcuts for controlling video playback and navigation": "動画の再生とナビゲーションを操作するショートカット", "Time Series Controls": "時系列コントロール", "Shortcuts for manipulating time series data regions": "時系列データ領域を操作するショートカット", "Image Gallery Navigation": "画像ギャラリーナビゲーション", "Shortcuts for navigating between images in multi-image tasks": "複数画像タスクで画像間を移動するショートカット", "Paragraph Navigation": "段落ナビゲーション", "Shortcuts for navigating phrases and regions in paragraph/dialogue view": "段落/対話ビューでフレーズやリージョンを移動するショートカット"};

const tHotkeyText = (en) => (isJapaneseLocale ? HOTKEY_JA_TRANSLATIONS[en] ?? en : en);

export const DEFAULT_HOTKEYS = [
  // Annotation Controls
  {
    id: 100,
    section: "annotation",
    element: "annotation:submit",
    label: tHotkeyText("Submit Annotation"),
    key: "ctrl+enter",
    description: tHotkeyText("Submit the current annotation"),
    active: true,
  },
  {
    id: 200,
    section: "annotation",
    element: "annotation:skip",
    label: tHotkeyText("Skip Task"),
    key: "ctrl+space",
    description: tHotkeyText("Skip the current task"),
    active: true,
  },
  {
    id: 300,
    section: "annotation",
    element: "annotation:undo",
    label: tHotkeyText("Undo"),
    key: "ctrl+z",
    description: tHotkeyText("Undo last action"),
    active: true,
  },
  {
    id: 400,
    section: "annotation",
    element: "annotation:redo",
    label: tHotkeyText("Redo"),
    key: "ctrl+shift+z",
    description: tHotkeyText("Redo previously undone action"),
    active: true,
  },

  // Data Manager
  {
    id: 500,
    section: "data_manager",
    element: "dm.focus-previous",
    label: tHotkeyText("Focus Previous Task"),
    key: "shift+up",
    description: tHotkeyText("Move focus to the previous task"),
    active: true,
  },
  {
    id: 600,
    section: "data_manager",
    element: "dm.focus-next",
    label: tHotkeyText("Focus Next Task"),
    key: "shift+down",
    description: tHotkeyText("Move focus to the next task"),
    active: true,
  },
  {
    id: 700,
    section: "data_manager",
    element: "dm.close-labeling",
    label: tHotkeyText("Focus Closed Task"),
    key: "shift+left",
    description: tHotkeyText("Focus on the closed task column"),
    active: true,
  },
  {
    id: 800,
    section: "data_manager",
    element: "dm.open-labeling",
    label: tHotkeyText("Focus Open Task"),
    key: "shift+right",
    description: tHotkeyText("Focus on the open task column"),
    active: true,
  },
  {
    id: 900,
    section: "data_manager",
    element: "dm.toggle-bulk-sidebar-minimization",
    label: tHotkeyText("Toggle Bulk Sidebar"),
    key: "shift+.",
    description: tHotkeyText("Minimize or expand bulk actions sidebar"),
    active: true,
  },

  // Region Management
  {
    id: 1100,
    section: "regions",
    element: "region:delete-all",
    label: tHotkeyText("Delete All Regions"),
    key: "ctrl+backspace",
    description: tHotkeyText("Remove all regions"),
    active: true,
  },
  {
    id: 1200,
    section: "regions",
    element: "region:focus",
    label: tHotkeyText("Focus First Region"),
    key: "enter",
    description: tHotkeyText("Move focus to the first focusable region"),
    active: true,
  },
  {
    id: 1300,
    section: "regions",
    element: "region:relation",
    label: tHotkeyText("Create Region Relation"),
    key: "alt+r",
    description: tHotkeyText("Create a relation between selected regions"),
    active: true,
  },
  {
    id: 1400,
    section: "regions",
    element: "region:visibility",
    label: tHotkeyText("Toggle Region Visibility"),
    key: "alt+h",
    description: tHotkeyText("Show or hide the selected region"),
    active: true,
  },
  {
    id: 1500,
    section: "regions",
    element: "region:visibility-all",
    label: tHotkeyText("Toggle All Region Visibility"),
    key: "ctrl+h",
    description: tHotkeyText("Show or hide all regions"),
    active: true,
  },
  {
    id: 1600,
    section: "regions",
    element: "region:lock",
    label: tHotkeyText("Lock Region"),
    key: "alt+l",
    description: tHotkeyText("Lock or unlock the selected region"),
    active: true,
  },
  {
    id: 1700,
    section: "regions",
    element: "region:meta",
    label: tHotkeyText("Edit Region Metadata"),
    key: "alt+m",
    description: tHotkeyText("Edit metadata for selected region"),
    active: true,
  },
  {
    id: 1800,
    section: "regions",
    element: "region:unselect",
    label: tHotkeyText("Unselect Region"),
    key: "u",
    description: tHotkeyText("Deselect the currently selected region"),
    active: true,
  },
  {
    id: 1900,
    section: "regions",
    element: "region:exit",
    label: tHotkeyText("Exit Region Mode"),
    key: "escape",
    description: tHotkeyText("Exit relation mode and unselect region"),
    active: true,
  },
  {
    id: 2000,
    section: "regions",
    element: "region:delete",
    label: tHotkeyText("Delete Selected Region"),
    key: "backspace",
    description: tHotkeyText("Delete currently selected region"),
    active: true,
  },
  {
    id: 2100,
    section: "regions",
    element: "region:cycle",
    label: tHotkeyText("Cycle Regions"),
    key: "alt+.",
    description: tHotkeyText("Cycle through all regions"),
    active: true,
  },
  {
    id: 2200,
    section: "regions",
    element: "region:duplicate",
    label: tHotkeyText("Duplicate Region"),
    key: "ctrl+d",
    description: tHotkeyText("Create a copy of the selected region"),
    active: true,
  },
  {
    id: 2300,
    section: "regions",
    element: "segment:delete",
    label: tHotkeyText("Delete Segment"),
    key: "delete",
    description: tHotkeyText("Delete selected segment"),
    active: true,
  },

  // Editor - Audio Controls
  {
    id: 2400,
    section: "audio",
    element: "audio:back",
    label: tHotkeyText("Rewind 1 Second"),
    key: "ctrl+b",
    description: tHotkeyText("Rewind the audio by 1 second"),
    active: true,
  },
  {
    id: 2500,
    section: "audio",
    element: "audio:playpause",
    label: tHotkeyText("Play / Pause Audio"),
    key: "ctrl+p",
    description: tHotkeyText("Toggle audio playback"),
    active: true,
  },
  {
    id: 2600,
    section: "audio",
    element: "audio:step-backward",
    label: tHotkeyText("Step Back"),
    key: "alt+a",
    description: tHotkeyText("Step back one frame"),
    active: true,
  },
  {
    id: 2700,
    section: "audio",
    element: "audio:step-forward",
    label: tHotkeyText("Step Forward"),
    key: "alt+d",
    description: tHotkeyText("Step forward one frame"),
    active: true,
  },

  // Editor - Video Controls
  {
    id: 2800,
    section: "video",
    element: "media:playpause",
    label: tHotkeyText("Play / Pause Video"),
    key: "ctrl+alt+space",
    description: tHotkeyText("Toggle video playback"),
    active: true,
  },
  {
    id: 2900,
    section: "video",
    element: "media:step-backward",
    label: tHotkeyText("Step Back"),
    key: "alt+left",
    description: tHotkeyText("Step one frame backward"),
    active: true,
  },
  {
    id: 3000,
    section: "video",
    element: "media:step-forward",
    label: tHotkeyText("Step Forward"),
    key: "alt+right",
    description: tHotkeyText("Step one frame forward"),
    active: true,
  },
  {
    id: 3100,
    section: "video",
    element: "video:keyframe-backward",
    label: tHotkeyText("Previous Keyframe"),
    key: "ctrl+alt+left",
    description: tHotkeyText("Jump to previous keyframe"),
    active: true,
  },
  {
    id: 3200,
    section: "video",
    element: "video:keyframe-forward",
    label: tHotkeyText("Next Keyframe"),
    key: "ctrl+alt+right",
    description: tHotkeyText("Jump to next keyframe"),
    active: true,
  },
  {
    id: 3300,
    section: "video",
    element: "video:backward",
    label: tHotkeyText("Seek Backward"),
    key: "alt+left",
    description: tHotkeyText("Seek video backward"),
    active: true,
  },
  {
    id: 3400,
    section: "video",
    element: "video:rewind",
    label: tHotkeyText("First Frame"),
    key: "shift+ctrl+alt+left",
    description: tHotkeyText("Jump to first frame"),
    active: true,
  },
  {
    id: 3500,
    section: "video",
    element: "video:forward",
    label: tHotkeyText("Seek Forward"),
    key: "shift+alt+right",
    description: tHotkeyText("Seek video forward"),
    active: true,
  },
  {
    id: 3600,
    section: "video",
    element: "video:fastforward",
    label: tHotkeyText("Last Frame"),
    key: "shift+ctrl+alt+right",
    description: tHotkeyText("Jump to last frame"),
    active: true,
  },
  {
    id: 3700,
    section: "video",
    element: "video:hop-backward",
    label: tHotkeyText("Hop Backward"),
    key: "shift+alt+left",
    description: tHotkeyText("Hop backward quickly"),
    active: true,
  },
  {
    id: 3800,
    section: "video",
    element: "video:hop-forward",
    label: tHotkeyText("Hop Forward"),
    key: "shift+alt+right",
    description: tHotkeyText("Hop forward quickly"),
    active: true,
  },

  // Editor - Time Series Controls
  {
    id: 3900,
    section: "timeseries",
    element: "ts:grow-left",
    label: tHotkeyText("Extend Left"),
    key: "left",
    description: tHotkeyText("Extend the region to the left"),
    active: true,
  },
  {
    id: 4000,
    section: "timeseries",
    element: "ts:grow-right",
    label: tHotkeyText("Extend Right"),
    key: "right",
    description: tHotkeyText("Extend the region to the right"),
    active: true,
  },
  {
    id: 4100,
    section: "timeseries",
    element: "ts:shrink-left",
    label: tHotkeyText("Shrink Left"),
    key: "alt+left",
    description: tHotkeyText("Shrink the region from the left"),
    active: true,
  },
  {
    id: 4200,
    section: "timeseries",
    element: "ts:shrink-right",
    label: tHotkeyText("Shrink Right"),
    key: "alt+right",
    description: tHotkeyText("Shrink the region from the right"),
    active: true,
  },
  {
    id: 4300,
    section: "timeseries",
    element: "ts:grow-left-large",
    label: tHotkeyText("Extend Left (Large)"),
    key: "shift+left",
    description: tHotkeyText("Extend region left significantly"),
    active: true,
  },
  {
    id: 4400,
    section: "timeseries",
    element: "ts:grow-right-large",
    label: tHotkeyText("Extend Right (Large)"),
    key: "shift+right",
    description: tHotkeyText("Extend region right significantly"),
    active: true,
  },
  {
    id: 4500,
    section: "timeseries",
    element: "ts:shrink-left-large",
    label: tHotkeyText("Shrink Left (Large)"),
    key: "shift+alt+left",
    description: tHotkeyText("Shrink region from left significantly"),
    active: true,
  },
  {
    id: 4600,
    section: "timeseries",
    element: "ts:shrink-right-large",
    label: tHotkeyText("Shrink Right (Large)"),
    key: "shift+alt+right",
    description: tHotkeyText("Shrink region from right significantly"),
    active: true,
  },

  // Image Gallery Controls
  {
    id: 4700,
    section: "image_gallery",
    element: "image:prev",
    label: tHotkeyText("Previous Image"),
    key: "ctrl+left",
    description: tHotkeyText("View previous image"),
    active: true,
  },
  {
    id: 4800,
    section: "image_gallery",
    element: "image:next",
    label: tHotkeyText("Next Image"),
    key: "ctrl+right",
    description: tHotkeyText("View next image"),
    active: true,
  },

  {
    id: 5000,
    section: "tools",
    element: "tool:zoom-in",
    label: tHotkeyText("Zoom In"),
    key: "ctrl+plus",
    description: tHotkeyText("Zoom in on the image"),
    active: true,
  },
  {
    id: 5100,
    section: "tools",
    element: "tool:pan-image",
    label: tHotkeyText("Pan Image"),
    key: "H",
    description: tHotkeyText("Pan around the image"),
    active: true,
  },
  {
    id: 5200,
    section: "tools",
    element: "tool:zoom-to-fit",
    label: tHotkeyText("Zoom to Fit"),
    key: "shift+1",
    description: tHotkeyText("Zoom to fit the full image in view"),
    active: true,
  },
  {
    id: 5300,
    section: "tools",
    element: "tool:zoom-to-actual",
    label: tHotkeyText("Zoom to 100%"),
    key: "shift+2",
    description: tHotkeyText("Zoom to actual image size (100%)"),
    active: true,
  },
  {
    id: 5400,
    section: "tools",
    element: "tool:zoom-out",
    label: tHotkeyText("Zoom Out"),
    key: "ctrl+minus",
    description: tHotkeyText("Zoom out of the image"),
    active: true,
  },
  {
    id: 5401,
    section: "tools",
    element: "tool:move",
    label: tHotkeyText("Move Tool"),
    key: "V",
    description: tHotkeyText("Select the move tool to reposition annotations"),
    active: true,
  },
  {
    id: 5402,
    section: "tools",
    element: "tool:brush",
    label: tHotkeyText("Brush Tool"),
    key: "B",
    description: tHotkeyText("Select the brush tool"),
    active: true,
  },

  {
    id: 5500,
    section: "tools",
    element: "tool:ellipse",
    label: tHotkeyText("Ellipse Tool"),
    key: "O",
    description: tHotkeyText("Select the ellipse tool"),
    active: true,
  },
  {
    id: 5600,
    section: "tools",
    element: "tool:eraser",
    label: tHotkeyText("Eraser Tool"),
    key: "E",
    description: tHotkeyText("Select the eraser tool"),
    active: true,
  },
  {
    id: 5700,
    section: "tools",
    element: "tool:auto-detect",
    label: tHotkeyText("Auto Detect"),
    key: "M",
    description: tHotkeyText("Use the auto-detect tool to automatically suggest regions"),
    active: true,
  },
  {
    id: 5900,
    section: "tools",
    element: "tool:key-point",
    label: tHotkeyText("Key Point Tool"),
    key: "K",
    description: tHotkeyText("Select the key point annotation tool"),
    active: true,
  },
  {
    id: 6000,
    section: "tools",
    element: "tool:magic-wand",
    label: tHotkeyText("Magic Wand"),
    key: "W",
    description: tHotkeyText("Select the magic wand tool for smart region selection"),
    active: true,
  },
  {
    id: 6100,
    section: "tools",
    element: "tool:polygon",
    label: tHotkeyText("Polygon Tool"),
    key: "P",
    description: tHotkeyText("Select the polygon annotation tool"),
    active: true,
  },
  {
    id: 6200,
    section: "tools",
    element: "tool:rect",
    label: tHotkeyText("Rectangle Tool"),
    key: "R",
    description: tHotkeyText("Select the rectangle annotation tool"),
    active: true,
  },
  {
    id: 6201,
    section: "tools",
    element: "tool:rect-3point",
    label: tHotkeyText("3-Point Rectangle"),
    key: "shift+R",
    description: tHotkeyText("Draw a rotated rectangle using 3-point selection"),
    active: true,
  },

  {
    id: 6300,
    section: "tools",
    element: "tool:rotate-left",
    label: tHotkeyText("Rotate Left"),
    key: "alt+left",
    description: tHotkeyText("Rotate the image 90° to the left"),
    active: true,
  },
  {
    id: 6400,
    section: "tools",
    element: "tool:rotate-right",
    label: tHotkeyText("Rotate Right"),
    key: "alt+right",
    description: tHotkeyText("Rotate the image 90° to the right"),
    active: true,
  },
  {
    id: 6700,
    section: "tools",
    element: "tool:decrease-tool",
    label: tHotkeyText("Decrease Tool Size"),
    key: "[",
    description: tHotkeyText("Decrease tool size"),
    active: true,
  },
  {
    id: 6800,
    section: "tools",
    element: "tool:increase-tool",
    label: tHotkeyText("Increase Tool Size"),
    key: "]",
    description: tHotkeyText("Increase tool size"),
    active: true,
  },

  // Paragraph Navigation
  {
    id: 6900,
    section: "paragraphs",
    element: "phrases:next-phrase",
    label: tHotkeyText("Next Phrase"),
    key: "ctrl+down",
    description: tHotkeyText("Navigate to the next phrase in paragraph view"),
    active: true,
  },
  {
    id: 7000,
    section: "paragraphs",
    element: "phrases:previous-phrase",
    label: tHotkeyText("Previous Phrase"),
    key: "ctrl+up",
    description: tHotkeyText("Navigate to the previous phrase in paragraph view"),
    active: true,
  },
  {
    id: 7100,
    section: "paragraphs",
    element: "phrases:select_all_annotate",
    label: tHotkeyText("Select All and Annotate"),
    key: "ctrl+shift+a",
    description: tHotkeyText("Select all text in current phrase and create annotation"),
    active: true,
  },
  {
    id: 7200,
    section: "paragraphs",
    element: "phrases:next-region",
    label: tHotkeyText("Next Region in Phrase"),
    key: "ctrl+right",
    description: tHotkeyText("Navigate to the next region within current phrase"),
    active: true,
  },
  {
    id: 7300,
    section: "paragraphs",
    element: "phrases:previous-region",
    label: tHotkeyText("Previous Region in Phrase"),
    key: "ctrl+left",
    description: tHotkeyText("Navigate to the previous region within current phrase"),
    active: true,
  },
];

export const HOTKEY_SECTIONS = [
  {
    id: "annotation",
    title: tHotkeyText("Annotation Actions"),
    description: tHotkeyText("Shortcuts for common annotation tasks like submit, skip, undo and redo"),
  },

  {
    id: "data_manager",
    title: tHotkeyText("Data Manager"),
    description: tHotkeyText("Shortcuts for navigating and managing tasks in Project's Data Manager"),
  },

  {
    id: "regions",
    title: tHotkeyText("Region Management"),
    description: tHotkeyText("Shortcuts for creating, selecting and manipulating annotation regions"),
  },

  {
    id: "tools",
    title: tHotkeyText("Tools"),
    description: tHotkeyText("Shortcuts for controlling tools panel when labeling images"),
  },

  {
    id: "audio",
    title: tHotkeyText("Audio Controls"),
    description: tHotkeyText("Shortcuts for controlling audio playback and navigation"),
  },
  {
    id: "video",
    title: tHotkeyText("Video Controls"),
    description: tHotkeyText("Shortcuts for controlling video playback and navigation"),
  },
  {
    id: "timeseries",
    title: tHotkeyText("Time Series Controls"),
    description: tHotkeyText("Shortcuts for manipulating time series data regions"),
  },
  {
    id: "image_gallery",
    title: tHotkeyText("Image Gallery Navigation"),
    description: tHotkeyText("Shortcuts for navigating between images in multi-image tasks"),
  },
  {
    id: "paragraphs",
    title: tHotkeyText("Paragraph Navigation"),
    description: tHotkeyText("Shortcuts for navigating phrases and regions in paragraph/dialogue view"),
  },
];

/**
 * URL patterns mapped to their corresponding hotkey sections
 * Used to automatically determine which shortcuts to display based on current page
 */
export const URL_TO_SECTION_MAPPING = [
  {
    regex: /\/projects\/\d+\/data\/?\?.*task=\d+/i,
    section: ["annotation", "regions"],
  },
  {
    regex: /\/projects\/\d+\/data\/?$/i,
    section: "data_manager",
  },
];
